//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Donor_Information
    {
        public int DonorInfo_Id { get; set; }
        public int Donor_No { get; set; }
        public Nullable<bool> Surgery { get; set; }
        public Nullable<bool> Blood_pressure { get; set; }
        public Nullable<bool> Blood_Diabetes { get; set; }
        public Nullable<bool> Heart_Disease { get; set; }
        public Nullable<bool> Medicine { get; set; }
        public string Medicine_Text { get; set; }
        public Nullable<bool> Smoker { get; set; }
        public Nullable<bool> Other_Problems { get; set; }
        public string Other_Problems_Text { get; set; }
        [Required]
        [Range(55, 200)]
        public int Weight { get; set; }
        public int User_No { get; set; }
        public System.DateTime Date { get; set; }
        public byte IsDonate { get; set; }
    
        public virtual Donor Donor { get; set; }
        public virtual User User { get; set; }
    }
}
