//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Donor()
        {
            this.Collected_Blood = new HashSet<Collected_Blood>();
            this.Donor_Information = new HashSet<Donor_Information>();
        }
    
        public int Donar_Id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public System.DateTime Date_of_Birth { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
        public string National_ID { get; set; }
        public string Email { get; set; }
        public string Donate_Type { get; set; }
        public string Patient_Name { get; set; }
        public Nullable<int> Patient_Relation_No { get; set; }
        public int User_No { get; set; }
        public Nullable<byte> CanDonate { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Collected_Blood> Collected_Blood { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Donor_Information> Donor_Information { get; set; }
        public virtual Patient_Relation Patient_Relation { get; set; }
        public virtual User User { get; set; }
    }
}
