//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Outgoing_Blood
    {
        public int Outgoing_Id { get; set; }
        public int Collection_No { get; set; }
        public Nullable<int> Patient_No { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Collected_Blood Collected_Blood { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
