//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwIncomingInfo
    {
        public System.DateTime IncomingDate { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Donate_Type { get; set; }
        public string National_ID { get; set; }
        public string Patient_Name { get; set; }
        public Nullable<System.DateTime> DonatingDate { get; set; }
        public string Type_Name { get; set; }
        public int Hemo { get; set; }
        public string Username { get; set; }
    }
}
