//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwRegisteredDonor
    {
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Gender { get; set; }
        public string Telephone { get; set; }
        public string Donate_Type { get; set; }
        public string Patient_Name { get; set; }
        public string Patient_Relation_Name { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
