//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwStatusInfo
    {
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public bool Blood_Status_No { get; set; }
        public string Reason { get; set; }
        public string Type_Name { get; set; }
        public string Username { get; set; }
    }
}
