//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwStatusInfo
    {
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public bool Blood_Status_No { get; set; }
        public string Reason { get; set; }
        public string Type_Name { get; set; }
        public string Username { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public System.DateTime Date_of_Birth { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
        public string National_ID { get; set; }
        public string Email { get; set; }
        public string Donate_Type { get; set; }
        public int Donar_Id { get; set; }
        public Nullable<byte> CanDonate { get; set; }
        public int ColIection_Id { get; set; }
        public int Blood_Type_Id { get; set; }
        public int Id { get; set; }
        public int Authority { get; set; }
        public string Patient_Relation_Name { get; set; }
        public string Patiant_Name { get; set; }
        public bool IsUsed { get; set; }
        public int Incoming_Id { get; set; }
        public System.DateTime IncDate { get; set; }
        public double Hemo { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
    }
}
