//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwUserEntry
    {
        public string Username { get; set; }
        public int Authority { get; set; }
        public string User_Type_Name { get; set; }
        public int Donar_Id { get; set; }
        public int ColIection_Id { get; set; }
        public int DonorInfo_Id { get; set; }
    }
}
